# Generated by Django 5.2.1 on 2025-07-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GlassPack_site', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(to='GlassPack_site.category'),
        ),
    ]
