# Generated by Django 5.2.1 on 2025-07-04 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GlassPack_site', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FooterData',
            new_name='FooterInfo',
        ),
    ]
