# Generated by Django 5.2.1 on 2025-07-19 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GlassPack_site', '0002_remove_product_categories_product_categories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactText',
            new_name='ContactInfo',
        ),
        migrations.AlterModelOptions(
            name='aboutinfo',
            options={'verbose_name': '5. About us page information', 'verbose_name_plural': '5. About us page information'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '2. Categories', 'verbose_name_plural': '2. Categories'},
        ),
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name': '6. Contact us page information', 'verbose_name_plural': '6. Contact us page information'},
        ),
        migrations.AlterModelOptions(
            name='footerinfo',
            options={'verbose_name': '3. Footer information', 'verbose_name_plural': '3. Footer information'},
        ),
        migrations.AlterModelOptions(
            name='indexcontent',
            options={'verbose_name': '4. Home page information', 'verbose_name_plural': '4. Home page information'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '1. Products', 'verbose_name_plural': '1. Products'},
        ),
    ]
