# Generated by Django 5.2.1 on 2025-07-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GlassPack_site', '0004_aboutinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('subtitle', models.CharField(max_length=250)),
                ('mission_intro', models.TextField(max_length=350)),
                ('mission_details', models.TextField(max_length=350)),
                ('contact_text', models.CharField(max_length=150)),
                ('products_subtitle', models.TextField(max_length=500)),
            ],
        ),
    ]
