# Generated by Django 5.2.1 on 2025-07-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GlassPack_site', '0005_indexcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('product_type', models.CharField(choices=[('bottles', 'Bottles'), ('jars', 'Jars')], max_length=10)),
                ('volume', models.IntegerField()),
                ('height', models.IntegerField()),
                ('image', models.ImageField(upload_to='products/')),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
