# Generated by Django 5.2.1 on 2025-07-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GlassPack_site', '0007_product_slug_alter_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='diameter',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='finish_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
    ]
