# Generated by Django 5.2.5 on 2025-10-09 14:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=255)),
                ('comment', models.TextField(max_length=1000, validators=[django.core.validators.MinLengthValidator(10)])),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '9. User messages',
                'verbose_name_plural': '9. User messages',
            },
        ),
    ]
