# Generated by Django 5.2.5 on 2025-11-17 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glasspack_users', '0003_alter_usermessage_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermessage',
            options={'verbose_name': '5. User messages', 'verbose_name_plural': '5. User messages'},
        ),
    ]
