# Generated by Django 5.2.1 on 2025-08-05 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': '7. About us page information',
                'verbose_name_plural': '7. About us page information',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '4. Categories',
                'verbose_name_plural': '4. Categories',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '3. Colors',
                'verbose_name_plural': '3. Colors',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.TextField()),
            ],
            options={
                'verbose_name': '8. Contact us page information',
                'verbose_name_plural': '8. Contact us page information',
            },
        ),
        migrations.CreateModel(
            name='FinishType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '2. Types of finish',
                'verbose_name_plural': '2. Types of finish',
            },
        ),
        migrations.CreateModel(
            name='FooterInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('company_info', models.TextField()),
                ('address', models.CharField(max_length=100)),
                ('work_time', models.CharField(max_length=50)),
                ('registration_number', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': '5. Footer information',
                'verbose_name_plural': '5. Footer information',
            },
        ),
        migrations.CreateModel(
            name='IndexContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('subtitle', models.CharField(max_length=250)),
                ('mission_intro', models.TextField(max_length=350)),
                ('mission_details', models.TextField(max_length=350)),
                ('contact_text', models.CharField(max_length=150)),
                ('products_subtitle', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name': '6. Home page information',
                'verbose_name_plural': '6. Home page information',
            },
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=255)),
                ('comment', models.TextField(max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '9. User messages',
                'verbose_name_plural': '9. User messages',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('volume', models.IntegerField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('diameter', models.IntegerField()),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('image', models.ImageField(upload_to='products/')),
                ('is_published', models.BooleanField()),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(to='GlassPack_site.category')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='GlassPack_site.color')),
                ('finish_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='GlassPack_site.finishtype')),
            ],
            options={
                'verbose_name': '1. Products',
                'verbose_name_plural': '1. Products',
            },
        ),
    ]
