# Generated by Django 5.2.5 on 2025-10-09 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glasspack_site', '0003_alter_usermessage_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserMessage',
        ),
    ]
