# Generated by Django 5.2.5 on 2025-10-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glasspack_site', '0004_delete_usermessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexcontent',
            name='mission_details',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='indexcontent',
            name='mission_intro',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='indexcontent',
            name='products_subtitle',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='indexcontent',
            name='subtitle',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='indexcontent',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
