# Generated by Django 5.2.5 on 2025-10-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glasspack_site', '0005_alter_indexcontent_mission_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
