# Generated by Django 5.2.5 on 2025-10-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glasspack_site', '0006_alter_product_is_published'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('volume__gte', 0)), name='volume_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('height__gte', 0)), name='height_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('weight__gte', 0)), name='weight_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('diameter__gte', 0)), name='diameter_gte_0'),
        ),
    ]
