# Generated by Django 5.2.5 on 2025-10-14 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glasspack_site', '0007_product_volume_gte_0_product_height_gte_0_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutInfo',
            new_name='AboutContent',
        ),
        migrations.RenameModel(
            old_name='ContactInfo',
            new_name='ContactContent',
        ),
        migrations.RenameModel(
            old_name='FooterInfo',
            new_name='FooterContent',
        ),
    ]
