# Generated by Django 5.2.5 on 2025-11-17 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glasspack_site', '0008_rename_aboutinfo_aboutcontent_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutContent',
        ),
        migrations.DeleteModel(
            name='ContactContent',
        ),
        migrations.DeleteModel(
            name='FooterContent',
        ),
        migrations.DeleteModel(
            name='IndexContent',
        ),
    ]
