# Generated by Django 5.2.5 on 2026-05-24 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': '4. Categories',
                'verbose_name_plural': '4. Categories',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': '3. Colors',
                'verbose_name_plural': '3. Colors',
            },
        ),
        migrations.CreateModel(
            name='FinishType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': '2. Types of finish',
                'verbose_name_plural': '2. Types of finish',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('volume', models.IntegerField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('diameter', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='products/')),
                ('is_published', models.BooleanField(default=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(to='core.category')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.color')),
                ('finish_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.finishtype')),
            ],
            options={
                'verbose_name': '1. Products',
                'verbose_name_plural': '1. Products',
                'constraints': [models.CheckConstraint(condition=models.Q(('volume__gte', 0)), name='volume_gte_0'), models.CheckConstraint(condition=models.Q(('height__gte', 0)), name='height_gte_0'), models.CheckConstraint(condition=models.Q(('weight__gte', 0)), name='weight_gte_0'), models.CheckConstraint(condition=models.Q(('diameter__gte', 0)), name='diameter_gte_0')],
            },
        ),
    ]
